version: '3.8'

services:
  users:
    container_name: cryptotalks-users
    restart: no
    build:
      context: ./services/users
      dockerfile: ./Dockerfile
    command: npm run start:dev
    volumes:
      - ./services/users:/usr/src/cryptotalks-users
    depends_on:
      - api
    ports:
      - ${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}
    networks:
      - cryptotalks-network
  front:
    container_name: cryptotalks-front
    restart: no
    build:
      context: ./services/front
      dockerfile: ./Dockerfile
    command: npm run dev
    volumes:
      - ./services/front:/usr/src/cryptotalks-front
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
  crypto-rates:
    container_name: cryptotalks-crypto-rates
    restart: no
    build:
      context: ./services/crypto-rates
      dockerfile: ./Dockerfile
    command: npm run start:dev
    volumes:
      - ./services/crypto-rates:/usr/src/cryptotalks-crypto-rates
    depends_on:
      - api
    ports:
      - ${CRYPTO_RATES_SERVICE_PORT}:${CRYPTO_RATES_SERVICE_PORT}
    networks:
      - cryptotalks-network
  auth:
    container_name: cryptotalks-auth
    restart: no
    build:
      context: ./services/auth
      dockerfile: ./Dockerfile
    command: npm run start:dev
    volumes:
      - ./services/auth:/usr/src/cryptotalks-auth
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    depends_on:
      - api
    networks:
      - cryptotalks-network
  posts:
    container_name: cryptotalks-posts
    restart: no
    build:
      context: ./services/posts
      dockerfile: ./Dockerfile
    command: npm run start:dev
    volumes:
      - ./services/posts:/usr/src/cryptotalks-posts
    ports:
      - ${POSTS_SERVICE_PORT}:${POSTS_SERVICE_PORT}
    depends_on:
      - api
    networks:
      - cryptotalks-network
  api:
    container_name: cryptotalks-api
    restart: no
    build:
      context: ./services/api
      dockerfile: ./Dockerfile
    command: npm run start:dev
    volumes:
      - ./services/api:/usr/src/cryptotalks-api
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - cryptotalks-network
  db:
    image: postgres
    container_name: cryptotalks-db
    restart: no
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - /:/data/postgres
    networks:
      - cryptotalks-network

networks:
  cryptotalks-network:
    driver: bridge
    external: true
