openapi: 3.0.0
paths:
  /api/posts/create:
    post:
      operationId: PostsController_createPost
      summary: Responsible for post creation
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePostDto"
      responses:
        "200":
          description: As a response function gets success message
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
      tags:
        - Posts
  /api/user/sign-up:
    post:
      operationId: UserController_signUp
      summary: Responsible for user account creation
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpDto"
      responses:
        "201":
          description: As a response function gets 2 tokens - refresh and access
      tags: &a1
        - User
  /api/user/sign-in:
    post:
      operationId: UserController_signIn
      summary: Responsible for user login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInDto"
      responses:
        "201":
          description: As a response function gets success message
      tags: *a1
info:
  title: Cryptotalks - API Gateway
  description: Documentation of Cryptotalks' API Gateway.
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreatePostDto:
      type: object
      properties:
        Title:
          type: string
          nullable: false
        Content:
          type: Array<string>
          nullable: false
      required:
        - Title
        - Content
    AccountConfirmationDto:
      type: object
      properties:
        Confirmation hash:
          type: string
          nullable: false
      required:
        - Confirmation hash
    SignUpDto:
      type: object
      properties:
        First name:
          type: string
          nullable: true
        Last name:
          type: string
          nullable: true
        Email:
          type: string
          nullable: false
        Password:
          type: string
          nullable: false
        Username:
          type: string
          nullable: false
        Twitter:
          type: string
          nullable: true
        LinkedIn:
          type: string
          nullable: true
        Personal website:
          type: string
          nullable: true
        Account title:
          type: string
          nullable: true
        Biography:
          type: string
          nullable: true
        Terms and conditions:
          type: boolean
          nullable: false
        Show personal email:
          type: boolean
          nullable: true
      required:
        - Email
        - Password
        - Username
        - Terms and conditions
    TokenPayloadDto:
      type: object
      properties:
        Id:
          type: string
          nullable: false
        Token type:
          type: access | refresh
          nullable: false
        User Id:
          type: string
          nullable: false
      required:
        - Id
        - Token type
        - User Id
    UpdateTokensDto:
      type: object
      properties:
        User Id:
          type: string
          nullable: false
        Email:
          type: string
          nullable: false
      required:
        - User Id
        - Email
    RefreshTokenDto:
      type: object
      properties:
        User Id:
          type: string
          nullable: false
        Token Id:
          type: string
          nullable: false
      required:
        - User Id
        - Token Id
    AccessTokenDto:
      type: object
      properties:
        User Id:
          type: string
          nullable: false
        Email:
          type: string
          nullable: false
      required:
        - User Id
        - Email
    SignInDto:
      type: object
      properties:
        Email:
          type: string
          nullable: false
        Password:
          type: string
          nullable: false
      required:
        - Email
        - Password
